version: "3"
rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php worker.php"

# Workflow and activity mesh service
temporal:
    address: ${TEMPORAL_ADDRESS:-localhost:7233}
    namespace: ${TEMPORAL_NAMESPACE:-default}
    activities:
        num_workers: 2

kv:
    harness:
        driver: memory
        config: { }

logs:
    mode: development
    level: info
