name: Continuous Integration

on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  latest-sdk-versions:
    runs-on: 'ubuntu-latest'
    outputs:
      go_latest: '1.27.0'
      typescript_latest: '1.10.0'
      java_latest: '1.24.0'
      python_latest: '1.6.0'
      php_latest: '2.10'
      csharp_latest: '1.1.2'
    steps:
      - run: 'echo noop'

  # Build cli and harnesses
  build-go:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] #  windows-latest - like 8x slower. Excluded for now since we're just building.
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print build information
        run: 'echo head_ref: "$GITHUB_HEAD_REF", ref: "$GITHUB_REF", os: ${{ matrix.os }}'
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'

      - run: go build -o temporal-features

  build-ts:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] #  windows-latest - like 8x slower. Excluded for now since we're just building.
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print build information
        run: 'echo head_ref: "$GITHUB_HEAD_REF", ref: "$GITHUB_REF", os: ${{ matrix.os }}'
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - run: npm ci
      - run: npm run build
      - run: npm run lint

  build-python:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] #  windows-latest - like 8x slower. Excluded for now since we're just building.
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print build information
        run: 'echo head_ref: "$GITHUB_HEAD_REF", ref: "$GITHUB_REF", os: ${{ matrix.os }}'
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python -m pip install --upgrade wheel poetry poethepoet
      - run: poetry install --no-root
      - run: poe lint

  build-php:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print build information
        run: 'echo head_ref: "$GITHUB_HEAD_REF", ref: "$GITHUB_REF", os: ${{ matrix.os }}'
      - uses: actions/checkout@v4
      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          extensions: dom, sockets, grpc, curl, protobuf

  build-java:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] #  windows-latest - like 8x slower. Excluded for now since we're just building.
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print build information
        run: 'echo head_ref: "$GITHUB_HEAD_REF", ref: "$GITHUB_REF", os: ${{ matrix.os }}'
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - run: ./gradlew build

  build-dotnet:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] #  windows-latest - like 8x slower. Excluded for now since we're just building.
    runs-on: ${{ matrix.os }}
    steps:
      - name: Print build information
        run: 'echo head_ref: "$GITHUB_HEAD_REF", ref: "$GITHUB_REF", os: ${{ matrix.os }}'
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
      - run: dotnet build
      - run: dotnet test

  feature-tests-ts:
    needs: latest-sdk-versions
    uses: ./.github/workflows/typescript.yaml
    with:
      version: ${{ needs.latest-sdk-versions.outputs.typescript_latest }}
      version-is-repo-ref: false
      features-repo-ref: ${{ github.head_ref }}
      features-repo-path: ${{ github.event.pull_request.head.repo.full_name }}

  feature-tests-go:
    needs: latest-sdk-versions
    uses: ./.github/workflows/go.yaml
    with:
      version: ${{ needs.latest-sdk-versions.outputs.go_latest }}
      version-is-repo-ref: false
      features-repo-ref: ${{ github.head_ref }}
      features-repo-path: ${{ github.event.pull_request.head.repo.full_name }}

  feature-tests-python:
    needs: latest-sdk-versions
    uses: ./.github/workflows/python.yaml
    with:
      version: ${{ needs.latest-sdk-versions.outputs.python_latest }}
      version-is-repo-ref: false
      features-repo-ref: ${{ github.head_ref }}
      features-repo-path: ${{ github.event.pull_request.head.repo.full_name }}

  feature-tests-php:
    needs: latest-sdk-versions
    uses: ./.github/workflows/php.yaml
    with:
      version: ${{ needs.latest-sdk-versions.outputs.php_latest }}
      version-is-repo-ref: false
      features-repo-ref: ${{ github.head_ref }}
      features-repo-path: ${{ github.event.pull_request.head.repo.full_name }}

  feature-tests-java:
    needs: latest-sdk-versions
    uses: ./.github/workflows/java.yaml
    with:
      version: 'v${{ needs.latest-sdk-versions.outputs.java_latest }}'
      version-is-repo-ref: false
      features-repo-ref: ${{ github.head_ref }}
      features-repo-path: ${{ github.event.pull_request.head.repo.full_name }}

  feature-tests-dotnet:
    needs: latest-sdk-versions
    uses: ./.github/workflows/dotnet.yaml
    with:
      version: ${{ needs.latest-sdk-versions.outputs.csharp_latest }}
      version-is-repo-ref: false
      features-repo-ref: ${{ github.head_ref }}
      features-repo-path: ${{ github.event.pull_request.head.repo.full_name }}

  build-docker-images:
    needs: latest-sdk-versions
    uses: ./.github/workflows/all-docker-images.yaml
    secrets: inherit
    # TODO: Find some way to automatically upgrade to "latest"
    with:
      do-push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      go-ver: 'v${{ needs.latest-sdk-versions.outputs.go_latest }}'
      ts-ver: 'v${{ needs.latest-sdk-versions.outputs.typescript_latest }}'
      java-ver: 'v${{ needs.latest-sdk-versions.outputs.java_latest }}'
      py-ver: 'v${{ needs.latest-sdk-versions.outputs.python_latest }}'
      php-ver: '${{ needs.latest-sdk-versions.outputs.php_latest }}'
      cs-ver: 'v${{ needs.latest-sdk-versions.outputs.csharp_latest }}'
